services:
  # Serviço do Redis (nosso "sistema de comandas")
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  # Serviço da aplicação web Django
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy

  # Serviço do Celery Worker (nossa "cozinha")
  worker:
    build: ./backend
    # Este comando inicia o worker do Celery
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy