# Generated by Django 5.2.5 on 2025-09-12 15:31

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Cartão Nubank, Conta Itaú, Dinheiro', max_length=100)),
                ('due_date', models.PositiveIntegerField(blank=True, help_text='Dia do vencimento da fatura (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
