# Generated by Django 5.2.5 on 2025-08-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='meta.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
