# Generated by Django 5.2.5 on 2025-09-11 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_sent', models.TextField()),
                ('response_received', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('duration_ms', models.PositiveIntegerField(help_text='Duração da chamada da API em milissegundos.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
