# Generated by Django 5.2.5 on 2025-09-12 13:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor da entrada', max_digits=10)),
                ('description', models.CharField(help_text='Descrição da entrada (ex: Salário, Freelance)', max_length=255)),
                ('income_type', models.CharField(choices=[('FIXA', 'Fixa'), ('VARIAVEL', 'Variável')], default='VARIAVEL', max_length=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
